const String SUPABASE_URL = 'https://rdwewunpvdrkjdfuaern.supabase.co';
const String SUPABASE_ANON_KEY =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkd2V3dW5wdmRya2pkZnVhZXJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ3NTE3MTUsImV4cCI6MjA4MDMyNzcxNX0.YYdmKWS1pDdkbh90YgFM1b4GD7oz4wtnCFri8cnAI0c';
